apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
  name: {{ include "demo-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: http
    name: http
  selector:
    {{- include "demo-app.selectorLabels" . | nindent 4 }}