replicas: 2

image:
  repository: "chhpe/color-app"
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  host: "rancher-green.hpelab.uk"
  path: "/app"

service:
  type: ClusterIP
  port: 8080

app:
  color: "green"

nodeSelector: {}

tolerations: []

affinity: {}

resources: {}

