apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app
  name: demo-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        name: color-app
        resources: {}
        ports:
        - containerPort: 8080
        env:
        - name: APP_COLOR
          value: {{ .Values.app.color }}
      serviceAccountName: demo-app
